
#CHARGE_TYPE 테이블 생성
CREATE TABLE CHARGE_TYPE (
	CHARGE_DO CHAR(30) NOT NULL, 
	PRIMARY KEY(CHARGE_DO)
);

#BRAND 테이블 생성
CREATE TABLE BRAND (
	BRAND_NAME CHAR(30) NOT NULL,
	CHARGE_DO CHAR(30) NOT NULL,
	FOREIGN KEY (CHARGE_DO) REFERENCES CHARGE_TYPE (CHARGE_DO),
	PRIMARY KEY(BRAND_NAME)
);

#충전소 테이블 생성
CREATE TABLE CHARGE (
	REGOIN_CODE CHAR(30) NOT NULL,
	CITY CHAR(100) NOT NULL,
	CHARGE_TYPE CHAR(200) NOT NULL,
	CHARGE_DO CHAR(30) NOT NULL,
	CHARGE_SPEED CHAR(30) NOT NULL,
	CHARGE_NAME CHAR(100) NOT NULL,
	CHARGE_ADDRESS CHAR(255) NOT NULL,
	PRIMARY KEY(CHARGE_NAME),
	FOREIGN KEY (CHARGE_DO) REFERENCES CHARGE_TYPE (CHARGE_DO),
	FOREIGN KEY (REGOIN_CODE) REFERENCES REGION (REGOIN_CODE)
);


#CAR 테이블 생성
CREATE TABLE CAR (
	CAR_CODE CHAR(10) NOT NULL,
	MODEL_NAME CHAR(50) NOT NULL UNIQUE,
	PRICE INT NOT NULL,
	CAR_TYPE CHAR(30) NOT NULL,
	FUEL_EFFICIENCY FLOAT NOT NULL,
	FUEL_TYPE CHAR(10) NOT NULL,
	MAX_DISTANCE INT NOT NULL,
	SUBSIDY INT NOT NULL,
	BRAND_NAME CHAR(30) NOT NULL,
	IMG_URL CHAR(200) NOT NULL,
	PRIMARY KEY(CAR_CODE),
	FOREIGN KEY (BRAND_NAME) REFERENCES BRAND(BRAND_NAME)
);


#지역 테이블 생성
CREATE TABLE REGION (
	REGOIN_CODE CHAR(30) NOT NULL,
	REGOIN_NAME CHAR(255) NOT NULL,
	PRIMARY KEY(REGOIN_CODE)
);
#VIEW 테이블 생성
CREATE VIEW CHARGE_STATISTICS AS
SELECT 
    r.REGOIN_NAME,  -- REGION 테이블의 지역 이름
    -- AC 충전기 개수
    SUM(CAST(JSON_UNQUOTE(JSON_EXTRACT(c.CHARGE_TYPE, '$."AC"')) AS UNSIGNED)) AS AC_COUNT,
    
    -- DC 충전기 개수 (DC차데모 + DC콤보)
    SUM(CAST(JSON_UNQUOTE(JSON_EXTRACT(c.CHARGE_TYPE, '$."DC차데모"')) AS UNSIGNED)) +
    SUM(CAST(JSON_UNQUOTE(JSON_EXTRACT(c.CHARGE_TYPE, '$."DC콤보"')) AS UNSIGNED)) AS DC_COUNT,
    
    -- 슈퍼차저 개수 (NACS)
    SUM(CAST(JSON_UNQUOTE(JSON_EXTRACT(c.CHARGE_TYPE, '$."NACS"')) AS UNSIGNED)) AS SUPERCHARGER_COUNT,
    
    -- 고속 충전기 개수 (CHARGE_SPEED='급속'인 경우)
    SUM(CASE WHEN c.CHARGE_SPEED = '급속' THEN 1 ELSE 0 END) AS FAST_CHARGER_COUNT,
    
    -- 완속 충전기 개수 (CHARGE_SPEED='완속'인 경우)
    SUM(CASE WHEN c.CHARGE_SPEED = '완속' THEN 1 ELSE 0 END) AS SLOW_CHARGER_COUNT
FROM CHARGE c
JOIN REGION r 
    ON c.REGOIN_CODE = r.REGOIN_CODE
GROUP BY r.REGOIN_NAME;
