INSERT INTO CHARGE_TYPE VALUES('국산');
INSERT INTO CHARGE_TYPE VALUES('수입');
INSERT INTO CHARGE_TYPE VALUES('국산/수입');

INSERT INTO BRAND VALUES('현대','국산');
INSERT INTO BRAND VALUES('기아','국산');
INSERT INTO BRAND VALUES('테슬라','수입');